export const customers = [
  {
    customer_id: 1,
    first_name: "Trudi",
    last_name: "Clemow",
    age: 50,
    country: "Gabon",
  },
  {
    customer_id: 2,
    first_name: "Jennica",
    last_name: "Ubanks",
    age: 50,
    country: "Canada",
  },
  {
    customer_id: 3,
    first_name: "Hilarius",
    last_name: "Royan",
    age: 37,
    country: "Somalia",
  },
  {
    customer_id: 4,
    first_name: "Karlis",
    last_name: "Pettyfar",
    age: 31,
    country: "Somalia",
  },
  {
    customer_id: 5,
    first_name: "Leoine",
    last_name: "Machin",
    age: 34,
    country: "Palestinian Territory",
  },
  {
    customer_id: 6,
    first_name: "Armand",
    last_name: "Skinn",
    age: 33,
    country: "Russia",
  },
  {
    customer_id: 7,
    first_name: "Henderson",
    last_name: "Extill",
    age: 57,
    country: "Argentina",
  },
  {
    customer_id: 8,
    first_name: "Alleen",
    last_name: "Rizzetti",
    age: 53,
    country: "Dominican Republic",
  },
  {
    customer_id: 9,
    first_name: "Vikki",
    last_name: "Eagleston",
    age: 45,
    country: "Brazil",
  },
  {
    customer_id: 10,
    first_name: "Aime",
    last_name: "Coulman",
    age: 53,
    country: "Paraguay",
  },
  {
    customer_id: 11,
    first_name: "Garnette",
    last_name: "Bye",
    age: 56,
    country: "Malta",
  },
  {
    customer_id: 12,
    first_name: "Meg",
    last_name: "Currm",
    age: 44,
    country: "Zambia",
  },
  {
    customer_id: 13,
    first_name: "Aubrie",
    last_name: "Ritzman",
    age: 24,
    country: "Indonesia",
  },
  {
    customer_id: 14,
    first_name: "Kit",
    last_name: "Start",
    age: 50,
    country: "Philippines",
  },
  {
    customer_id: 15,
    first_name: "Polly",
    last_name: "Gilliam",
    age: 57,
    country: "Indonesia",
  },
  {
    customer_id: 16,
    first_name: "Timoteo",
    last_name: "Adelsberg",
    age: 46,
    country: "Indonesia",
  },
  {
    customer_id: 17,
    first_name: "Derron",
    last_name: "Cakebread",
    age: 48,
    country: "Slovenia",
  },
  {
    customer_id: 18,
    first_name: "Warde",
    last_name: "Zanneli",
    age: 32,
    country: "Peru",
  },
  {
    customer_id: 19,
    first_name: "Mart",
    last_name: "Dorgan",
    age: 38,
    country: "Philippines",
  },
  {
    customer_id: 20,
    first_name: "Rolando",
    last_name: "Franiak",
    age: 59,
    country: "Kyrgyzstan",
  },
  {
    customer_id: 21,
    first_name: "Timmie",
    last_name: "Jiruch",
    age: 42,
    country: "Japan",
  },
  {
    customer_id: 22,
    first_name: "Bryon",
    last_name: "Blose",
    age: 22,
    country: "China",
  },
  {
    customer_id: 23,
    first_name: "Zsa zsa",
    last_name: "Ferrarotti",
    age: 53,
    country: "China",
  },
  {
    customer_id: 24,
    first_name: "Westbrooke",
    last_name: "Ratazzi",
    age: 35,
    country: "Guatemala",
  },
  {
    customer_id: 25,
    first_name: "Nikkie",
    last_name: "Whitear",
    age: 39,
    country: "Russia",
  },
  {
    customer_id: 26,
    first_name: "Nikoletta",
    last_name: "Duggen",
    age: 56,
    country: "Guam",
  },
  {
    customer_id: 27,
    first_name: "Zackariah",
    last_name: "Calender",
    age: 57,
    country: "Philippines",
  },
  {
    customer_id: 28,
    first_name: "Miller",
    last_name: "Evemy",
    age: 55,
    country: "El Salvador",
  },
  {
    customer_id: 29,
    first_name: "Dianemarie",
    last_name: "Kobiela",
    age: 58,
    country: "Portugal",
  },
  {
    customer_id: 30,
    first_name: "Kym",
    last_name: "Durrand",
    age: 24,
    country: "Philippines",
  },
  {
    customer_id: 31,
    first_name: "Norma",
    last_name: "MacLise",
    age: 36,
    country: "Colombia",
  },
  {
    customer_id: 32,
    first_name: "Butch",
    last_name: "Paulon",
    age: 26,
    country: "Czech Republic",
  },
  {
    customer_id: 33,
    first_name: "Culley",
    last_name: "Pinkerton",
    age: 46,
    country: "Poland",
  },
  {
    customer_id: 34,
    first_name: "Marybelle",
    last_name: "Landsman",
    age: 26,
    country: "Germany",
  },
  {
    customer_id: 35,
    first_name: "Aleta",
    last_name: "Arnaut",
    age: 53,
    country: "China",
  },
  {
    customer_id: 36,
    first_name: "Link",
    last_name: "Risbie",
    age: 30,
    country: "Indonesia",
  },
  {
    customer_id: 37,
    first_name: "Nonnah",
    last_name: "Swindles",
    age: 30,
    country: "China",
  },
  {
    customer_id: 38,
    first_name: "Reiko",
    last_name: "Gorman",
    age: 45,
    country: "Sweden",
  },
  {
    customer_id: 39,
    first_name: "Drusy",
    last_name: "Limb",
    age: 40,
    country: "China",
  },
  {
    customer_id: 40,
    first_name: "Cristobal",
    last_name: "Livesley",
    age: 46,
    country: "Nicaragua",
  },
  {
    customer_id: 41,
    first_name: "Ralf",
    last_name: "Mee",
    age: 60,
    country: "Philippines",
  },
  {
    customer_id: 42,
    first_name: "Arabelle",
    last_name: "Jouhning",
    age: 37,
    country: "China",
  },
  {
    customer_id: 43,
    first_name: "Vita",
    last_name: "Dressell",
    age: 35,
    country: "Thailand",
  },
  {
    customer_id: 44,
    first_name: "Padraic",
    last_name: "Broggelli",
    age: 59,
    country: "Estonia",
  },
  {
    customer_id: 45,
    first_name: "Cassi",
    last_name: "Morsley",
    age: 48,
    country: "Pakistan",
  },
  {
    customer_id: 46,
    first_name: "Melosa",
    last_name: "Mennithorp",
    age: 36,
    country: "Philippines",
  },
  {
    customer_id: 47,
    first_name: "Melamie",
    last_name: "Whimpenny",
    age: 49,
    country: "Sweden",
  },
  {
    customer_id: 48,
    first_name: "customer_ida",
    last_name: "Shorto",
    age: 34,
    country: "China",
  },
  {
    customer_id: 49,
    first_name: "Rurik",
    last_name: "MacDavitt",
    age: 50,
    country: "China",
  },
  {
    customer_id: 50,
    first_name: "Cleveland",
    last_name: "Doring",
    age: 49,
    country: "China",
  },
];

export const orders = [
  {
    order_id: 1,
    item: "Keyboard",
    amount: 400,
    customer_id: 4,
  },
  {
    order_id: 2,
    item: "Mouse",
    amount: 300,
    customer_id: 4,
  },
  {
    order_id: 3,
    item: "Monitor",
    amount: 12000,
    customer_id: 3,
  },
  {
    order_id: 4,
    item: "Keyboard",
    amount: 400,
    customer_id: 1,
  },
  {
    order_id: 5,
    item: "Mousepad",
    amount: 250,
    customer_id: 2,
  },
];

export const shippings = [
  { shipping_id: 1, status: "Pending", customer_id: 2 },
  { shipping_id: 2, status: "Pending", customer_id: 4 },
  { shipping_id: 3, status: "Delivered", customer_id: 3 },
  { shipping_id: 4, status: "Pending", customer_id: 5 },
  { shipping_id: 5, status: "Delivered", customer_id: 1 },
];
